name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app/Contents/Developer

jobs:
  test:
    name: Test
    runs-on: macOS-12
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: set -o pipefail && xcodebuild -scheme ProcessService-Package -destination "platform=macOS" build | xcpretty
